package SpiderCorba.SpiderDefinePackage;


/**
* SpiderCorba/SpiderDefinePackage/DownloadConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 20, 2018 4:30:11 PM ICT
*/

public final class DownloadConfig implements org.omg.CORBA.portable.IDLEntity
{
  public String cHomeId = null;
  public String monitorContent = null;
  public String downloadClusterId = null;
  public int mappingType = (int)0;
  public int timerInterval = (int)0;
  public int synStatus = (int)0;

  public DownloadConfig ()
  {
  } // ctor

  public DownloadConfig (String _cHomeId, String _monitorContent, String _downloadClusterId, int _mappingType, int _timerInterval, int _synStatus)
  {
    cHomeId = _cHomeId;
    monitorContent = _monitorContent;
    downloadClusterId = _downloadClusterId;
    mappingType = _mappingType;
    timerInterval = _timerInterval;
    synStatus = _synStatus;
  } // ctor

} // class DownloadConfig
