package SpiderCorba.SpiderDefinePackage;


/**
* SpiderCorba/SpiderDefinePackage/DownloadConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, July 26, 2018 4:57:47 PM ICT
*/

public final class DownloadConfig implements org.omg.CORBA.portable.IDLEntity
{
  public String cHomeId = null;
  public String monitorContent = null;
  public int mappingType = (int)0;

  public DownloadConfig ()
  {
  } // ctor

  public DownloadConfig (String _cHomeId, String _monitorContent, int _mappingType)
  {
    cHomeId = _cHomeId;
    monitorContent = _monitorContent;
    mappingType = _mappingType;
  } // ctor

} // class DownloadConfig
