package SpiderCorba.SpiderDefinePackage;


/**
* SpiderCorba/SpiderDefinePackage/DownloadConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Saturday, June 16, 2018 10:22:14 PM ICT
*/

public final class DownloadConfig implements org.omg.CORBA.portable.IDLEntity
{
  public String cHomeId = null;
  public String cMonitorId = null;
  public String downloadClusterId = null;
  public int timerInterval = (int)0;
  public int synStatus = (int)0;

  public DownloadConfig ()
  {
  } // ctor

  public DownloadConfig (String _cHomeId, String _cMonitorId, String _downloadClusterId, int _timerInterval, int _synStatus)
  {
    cHomeId = _cHomeId;
    cMonitorId = _cMonitorId;
    downloadClusterId = _downloadClusterId;
    timerInterval = _timerInterval;
    synStatus = _synStatus;
  } // ctor

} // class DownloadConfig
