package SpiderCorba.SpiderDefinePackage;


/**
* SpiderCorba/SpiderDefinePackage/CustomVideoInfor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Friday, December 20, 2019 2:42:57 PM ICT
*/

public final class CustomVideoInfor implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String videoId = null;

  public CustomVideoInfor ()
  {
  } // ctor

  public CustomVideoInfor (int _id, String _videoId)
  {
    id = _id;
    videoId = _videoId;
  } // ctor

} // class CustomVideoInfor
