package SpiderCorba.SpiderDefinePackage;


/**
* SpiderCorba/SpiderDefinePackage/UploadConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Friday, December 20, 2019 2:42:57 PM ICT
*/

public final class UploadConfig implements org.omg.CORBA.portable.IDLEntity
{
  public String vTitleTemp = null;
  public String vDescTemp = null;
  public String vTagsTemp = null;
  public boolean enableTitle = false;
  public boolean enableDes = false;
  public boolean enableTags = false;

  public UploadConfig ()
  {
  } // ctor

  public UploadConfig (String _vTitleTemp, String _vDescTemp, String _vTagsTemp, boolean _enableTitle, boolean _enableDes, boolean _enableTags)
  {
    vTitleTemp = _vTitleTemp;
    vDescTemp = _vDescTemp;
    vTagsTemp = _vTagsTemp;
    enableTitle = _enableTitle;
    enableDes = _enableDes;
    enableTags = _enableTags;
  } // ctor

} // class UploadConfig
