package SpiderUploadApp.SpiderFootSidePackage;

/**
* SpiderUploadApp/SpiderFootSidePackage/UploadInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 6, 2018 2:25:21 PM ICT
*/

public final class UploadInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderUploadApp.SpiderFootSidePackage.UploadInfo value = null;

  public UploadInfoHolder ()
  {
  }

  public UploadInfoHolder (SpiderUploadApp.SpiderFootSidePackage.UploadInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderUploadApp.SpiderFootSidePackage.UploadInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderUploadApp.SpiderFootSidePackage.UploadInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderUploadApp.SpiderFootSidePackage.UploadInfoHelper.type ();
  }

}
