package SpiderUploadApp.SpiderFootSidePackage;


/**
* SpiderUploadApp/SpiderFootSidePackage/UploadInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 6, 2018 2:25:21 PM ICT
*/

public final class UploadInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int jobId = (int)0;
  public String videoId = null;
  public String vTitle = null;
  public String vDesc = null;
  public String vTags = null;
  public String vThumbnail = null;
  public String vLocation = null;
  public boolean enableTitle = false;
  public boolean enableDes = false;
  public boolean enableTags = false;
  public int mappingId = (int)0;

  public UploadInfo ()
  {
  } // ctor

  public UploadInfo (int _jobId, String _videoId, String _vTitle, String _vDesc, String _vTags, String _vThumbnail, String _vLocation, boolean _enableTitle, boolean _enableDes, boolean _enableTags, int _mappingId)
  {
    jobId = _jobId;
    videoId = _videoId;
    vTitle = _vTitle;
    vDesc = _vDesc;
    vTags = _vTags;
    vThumbnail = _vThumbnail;
    vLocation = _vLocation;
    enableTitle = _enableTitle;
    enableDes = _enableDes;
    enableTags = _enableTags;
    mappingId = _mappingId;
  } // ctor

} // class UploadInfo
