package corba.variableDefinePackage;

/**
* corba/variableDefinePackage/CustomVideoInforHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

public final class CustomVideoInforHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.variableDefinePackage.CustomVideoInfor value = null;

  public CustomVideoInforHolder ()
  {
  }

  public CustomVideoInforHolder (corba.variableDefinePackage.CustomVideoInfor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.variableDefinePackage.CustomVideoInforHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.variableDefinePackage.CustomVideoInforHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.variableDefinePackage.CustomVideoInforHelper.type ();
  }

}
