package corba.variableDefinePackage;

/**
* corba/variableDefinePackage/DownloadConfigHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

public final class DownloadConfigHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.variableDefinePackage.DownloadConfig value = null;

  public DownloadConfigHolder ()
  {
  }

  public DownloadConfigHolder (corba.variableDefinePackage.DownloadConfig initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.variableDefinePackage.DownloadConfigHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.variableDefinePackage.DownloadConfigHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.variableDefinePackage.DownloadConfigHelper.type ();
  }

}
