package corba.variableDefinePackage;


/**
* corba/variableDefinePackage/RenderConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

public final class RenderConfig implements org.omg.CORBA.portable.IDLEntity
{
  public String renderCommand = null;

  public RenderConfig ()
  {
  } // ctor

  public RenderConfig (String _renderCommand)
  {
    renderCommand = _renderCommand;
  } // ctor

} // class RenderConfig
