package corba.variableDefinePackage;

/**
* corba/variableDefinePackage/RenderConfigHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

public final class RenderConfigHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.variableDefinePackage.RenderConfig value = null;

  public RenderConfigHolder ()
  {
  }

  public RenderConfigHolder (corba.variableDefinePackage.RenderConfig initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.variableDefinePackage.RenderConfigHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.variableDefinePackage.RenderConfigHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.variableDefinePackage.RenderConfigHelper.type ();
  }

}
