package corba.variableDefinePackage;

/**
* corba/variableDefinePackage/UploadConfigHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

public final class UploadConfigHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.variableDefinePackage.UploadConfig value = null;

  public UploadConfigHolder ()
  {
  }

  public UploadConfigHolder (corba.variableDefinePackage.UploadConfig initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.variableDefinePackage.UploadConfigHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.variableDefinePackage.UploadConfigHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.variableDefinePackage.UploadConfigHelper.type ();
  }

}
