package SpiderCorba;


/**
* SpiderCorba/RenderSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Saturday, June 16, 2018 11:03:08 PM ICT
*/

public interface RenderSideOperations  extends SpiderCorba.SpiderDefineOperations
{
  boolean createRenderJob (int jobId, SpiderCorba.SpiderDefinePackage.VideoInfo vInfo);
  boolean deleteRenderJob (int jobId);
  void deleteRenderdVideo (String vLocation);
} // interface RenderSideOperations
