package SpiderCorba;


/**
* SpiderCorba/RenderSideHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Saturday, June 16, 2018 11:03:08 PM ICT
*/

abstract public class RenderSideHelper
{
  private static String  _id = "IDL:SpiderCorba/RenderSide:1.0";

  public static void insert (org.omg.CORBA.Any a, SpiderCorba.RenderSide that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SpiderCorba.RenderSide extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SpiderCorba.RenderSideHelper.id (), "RenderSide");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SpiderCorba.RenderSide read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RenderSideStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SpiderCorba.RenderSide value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SpiderCorba.RenderSide narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SpiderCorba.RenderSide)
      return (SpiderCorba.RenderSide)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SpiderCorba._RenderSideStub stub = new SpiderCorba._RenderSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SpiderCorba.RenderSide unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SpiderCorba.RenderSide)
      return (SpiderCorba.RenderSide)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SpiderCorba._RenderSideStub stub = new SpiderCorba._RenderSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
