package SpiderCorba;

/**
* SpiderCorba/RenderSideHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 7, 2018 2:19:30 PM ICT
*/

public final class RenderSideHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderCorba.RenderSide value = null;

  public RenderSideHolder ()
  {
  }

  public RenderSideHolder (SpiderCorba.RenderSide initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderCorba.RenderSideHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderCorba.RenderSideHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderCorba.RenderSideHelper.type ();
  }

}
