package SpiderCorba;


/**
* SpiderCorba/SpiderDefineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 20, 2018 6:12:05 PM ICT
*/

public interface SpiderDefineOperations 
{
} // interface SpiderDefineOperations
