package SpiderCorba;


/**
* SpiderCorba/SpiderDefineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, August 8, 2018 5:32:45 PM ICT
*/

public interface SpiderDefineOperations 
{
} // interface SpiderDefineOperations
