package SpiderCorba;


/**
* SpiderCorba/SpiderDefineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Saturday, June 16, 2018 11:03:08 PM ICT
*/

public interface SpiderDefineOperations 
{
} // interface SpiderDefineOperations
