package SpiderCorba.UploadSidePackage;

/**
* SpiderCorba/UploadSidePackage/UploadConfigHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 7, 2018 2:10:52 PM ICT
*/

public final class UploadConfigHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderCorba.UploadSidePackage.UploadConfig value = null;

  public UploadConfigHolder ()
  {
  }

  public UploadConfigHolder (SpiderCorba.UploadSidePackage.UploadConfig initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderCorba.UploadSidePackage.UploadConfigHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderCorba.UploadSidePackage.UploadConfigHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderCorba.UploadSidePackage.UploadConfigHelper.type ();
  }

}
