package SpiderRenderApp;


/**
* SpiderRenderApp/SpiderFootSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Tuesday, May 29, 2018 2:49:54 PM ICT
*/

public interface SpiderFootSide extends SpiderFootSideOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SpiderFootSide
