package SpiderRenderApp;

/**
* SpiderRenderApp/SpiderFootSideHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Monday, June 4, 2018 3:41:36 PM ICT
*/

public final class SpiderFootSideHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderRenderApp.SpiderFootSide value = null;

  public SpiderFootSideHolder ()
  {
  }

  public SpiderFootSideHolder (SpiderRenderApp.SpiderFootSide initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderRenderApp.SpiderFootSideHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderRenderApp.SpiderFootSideHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderRenderApp.SpiderFootSideHelper.type ();
  }

}
