package SpiderAgentApp;


/**
* SpiderAgentApp/AgentSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 6, 2018 2:25:21 PM ICT
*/

public interface AgentSide extends AgentSideOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgentSide
