package SpiderAgentApp;


/**
* SpiderAgentApp/AgentSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, May 31, 2018 5:26:47 PM ICT
*/

public interface AgentSideOperations 
{
  void onDownloadStartup (String appId);
  void onRenderStartup (String appId);
  void onUploadStartup (String appId);
  long getLastSyncTime (int mappingId);
  void updateLastSyntime (int mappingId, long lastSyncTime);
  void updateDownloadedVideo (SpiderAgentApp.AgentSidePackage.VideoInfo vInfo);
  void updateRenderedVideo (int videoId, int processStatus, String videoLocation);
  void updateUploadedVideo (int videoId, int processStatus, String videoLocation);
} // interface AgentSideOperations
