package SpiderCorba;


/**
* SpiderCorba/SpiderDefineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Friday, December 20, 2019 2:42:57 PM ICT
*/

public interface SpiderDefineOperations 
{
} // interface SpiderDefineOperations
