package SpiderCorba;


/**
* SpiderCorba/SpiderBootSideHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Friday, December 20, 2019 2:42:57 PM ICT
*/

abstract public class SpiderBootSideHelper
{
  private static String  _id = "IDL:SpiderCorba/SpiderBootSide:1.0";

  public static void insert (org.omg.CORBA.Any a, SpiderCorba.SpiderBootSide that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SpiderCorba.SpiderBootSide extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SpiderCorba.SpiderBootSideHelper.id (), "SpiderBootSide");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SpiderCorba.SpiderBootSide read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SpiderBootSideStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SpiderCorba.SpiderBootSide value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SpiderCorba.SpiderBootSide narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SpiderCorba.SpiderBootSide)
      return (SpiderCorba.SpiderBootSide)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SpiderCorba._SpiderBootSideStub stub = new SpiderCorba._SpiderBootSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SpiderCorba.SpiderBootSide unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SpiderCorba.SpiderBootSide)
      return (SpiderCorba.SpiderBootSide)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SpiderCorba._SpiderBootSideStub stub = new SpiderCorba._SpiderBootSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
