package SpiderCorba;

/**
* SpiderCorba/SpiderBootSideHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Friday, December 20, 2019 2:42:57 PM ICT
*/

public final class SpiderBootSideHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderCorba.SpiderBootSide value = null;

  public SpiderBootSideHolder ()
  {
  }

  public SpiderBootSideHolder (SpiderCorba.SpiderBootSide initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderCorba.SpiderBootSideHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderCorba.SpiderBootSideHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderCorba.SpiderBootSideHelper.type ();
  }

}
