package SpiderCorba;


/**
* SpiderCorba/YoutubeAgentPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Friday, December 20, 2019 2:42:57 PM ICT
*/

public abstract class YoutubeAgentPOA extends org.omg.PortableServer.Servant
 implements SpiderCorba.YoutubeAgentOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getChannelInfo", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SpiderCorba/YoutubeAgent/getChannelInfo
       {
         String channelId = in.read_wstring ();
         org.omg.CORBA.StringHolder channelName = new org.omg.CORBA.StringHolder ();
         org.omg.CORBA.IntHolder videoNumber = new org.omg.CORBA.IntHolder ();
         org.omg.CORBA.IntHolder viewNUmber = new org.omg.CORBA.IntHolder ();
         org.omg.CORBA.IntHolder subcriber = new org.omg.CORBA.IntHolder ();
         org.omg.CORBA.IntHolder dateCreated = new org.omg.CORBA.IntHolder ();
         org.omg.CORBA.IntHolder status = new org.omg.CORBA.IntHolder ();
         this.getChannelInfo (channelId, channelName, videoNumber, viewNUmber, subcriber, dateCreated, status);
         out = $rh.createReply();
         out.write_wstring (channelName.value);
         out.write_long (videoNumber.value);
         out.write_long (viewNUmber.value);
         out.write_long (subcriber.value);
         out.write_long (dateCreated.value);
         out.write_long (status.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SpiderCorba/YoutubeAgent:1.0", 
    "IDL:SpiderCorba/SpiderDefine:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public YoutubeAgent _this() 
  {
    return YoutubeAgentHelper.narrow(
    super._this_object());
  }

  public YoutubeAgent _this(org.omg.CORBA.ORB orb) 
  {
    return YoutubeAgentHelper.narrow(
    super._this_object(orb));
  }


} // class YoutubeAgentPOA
