package SpiderAgentApp.AgentSidePackage;

/**
* SpiderAgentApp/AgentSidePackage/AuthenInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 6, 2018 2:25:21 PM ICT
*/

public final class AuthenInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderAgentApp.AgentSidePackage.AuthenInfo value = null;

  public AuthenInfoHolder ()
  {
  }

  public AuthenInfoHolder (SpiderAgentApp.AgentSidePackage.AuthenInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderAgentApp.AgentSidePackage.AuthenInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderAgentApp.AgentSidePackage.AuthenInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderAgentApp.AgentSidePackage.AuthenInfoHelper.type ();
  }

}
