package SpiderAgentApp.AgentSidePackage;

/**
* SpiderAgentApp/AgentSidePackage/ClusterInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Tuesday, June 5, 2018 5:14:34 PM ICT
*/

public final class ClusterInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderAgentApp.AgentSidePackage.ClusterInfo value = null;

  public ClusterInfoHolder ()
  {
  }

  public ClusterInfoHolder (SpiderAgentApp.AgentSidePackage.ClusterInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderAgentApp.AgentSidePackage.ClusterInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderAgentApp.AgentSidePackage.ClusterInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderAgentApp.AgentSidePackage.ClusterInfoHelper.type ();
  }

}
