package SpiderUploadApp;


/**
* SpiderUploadApp/SpiderFootSidePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Tuesday, June 5, 2018 5:14:34 PM ICT
*/

public abstract class SpiderFootSidePOA extends org.omg.PortableServer.Servant
 implements SpiderUploadApp.SpiderFootSideOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createUploadJob", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SpiderUploadApp/SpiderFootSide/createUploadJob
       {
         SpiderUploadApp.SpiderFootSidePackage.UploadInfo vInfo = SpiderUploadApp.SpiderFootSidePackage.UploadInfoHelper.read (in);
         boolean $result = false;
         $result = this.createUploadJob (vInfo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SpiderUploadApp/SpiderFootSide:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SpiderFootSide _this() 
  {
    return SpiderFootSideHelper.narrow(
    super._this_object());
  }

  public SpiderFootSide _this(org.omg.CORBA.ORB orb) 
  {
    return SpiderFootSideHelper.narrow(
    super._this_object(orb));
  }


} // class SpiderFootSidePOA
