package SpiderUploadApp;


/**
* SpiderUploadApp/SpiderFootSideHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 1, 2018 4:31:39 PM ICT
*/

abstract public class SpiderFootSideHelper
{
  private static String  _id = "IDL:SpiderUploadApp/SpiderFootSide:1.0";

  public static void insert (org.omg.CORBA.Any a, SpiderUploadApp.SpiderFootSide that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SpiderUploadApp.SpiderFootSide extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SpiderUploadApp.SpiderFootSideHelper.id (), "SpiderFootSide");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SpiderUploadApp.SpiderFootSide read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SpiderFootSideStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SpiderUploadApp.SpiderFootSide value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SpiderUploadApp.SpiderFootSide narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SpiderUploadApp.SpiderFootSide)
      return (SpiderUploadApp.SpiderFootSide)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SpiderUploadApp._SpiderFootSideStub stub = new SpiderUploadApp._SpiderFootSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SpiderUploadApp.SpiderFootSide unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SpiderUploadApp.SpiderFootSide)
      return (SpiderUploadApp.SpiderFootSide)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SpiderUploadApp._SpiderFootSideStub stub = new SpiderUploadApp._SpiderFootSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
