package SpiderUploadApp;


/**
* SpiderUploadApp/SpiderFootSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Tuesday, June 5, 2018 5:14:34 PM ICT
*/

public interface SpiderFootSideOperations 
{
  boolean createUploadJob (SpiderUploadApp.SpiderFootSidePackage.UploadInfo vInfo);
} // interface SpiderFootSideOperations
