package SpiderUploadApp;


/**
* SpiderUploadApp/SpiderFootSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 6, 2018 2:25:21 PM ICT
*/

public interface SpiderFootSide extends SpiderFootSideOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SpiderFootSide
