package SpiderCorba.SpiderDefinePackage;


/**
* SpiderCorba/SpiderDefinePackage/UploadConfigHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 21, 2018 10:14:48 AM ICT
*/

abstract public class UploadConfigHelper
{
  private static String  _id = "IDL:SpiderCorba/SpiderDefine/UploadConfig:1.0";

  public static void insert (org.omg.CORBA.Any a, SpiderCorba.SpiderDefinePackage.UploadConfig that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SpiderCorba.SpiderDefinePackage.UploadConfig extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "vTitleTemp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "vDescTemp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "vTagsTemp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "enableTitle",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "enableDes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[5] = new org.omg.CORBA.StructMember (
            "enableTags",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (SpiderCorba.SpiderDefinePackage.UploadConfigHelper.id (), "UploadConfig", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SpiderCorba.SpiderDefinePackage.UploadConfig read (org.omg.CORBA.portable.InputStream istream)
  {
    SpiderCorba.SpiderDefinePackage.UploadConfig value = new SpiderCorba.SpiderDefinePackage.UploadConfig ();
    value.vTitleTemp = istream.read_wstring ();
    value.vDescTemp = istream.read_wstring ();
    value.vTagsTemp = istream.read_wstring ();
    value.enableTitle = istream.read_boolean ();
    value.enableDes = istream.read_boolean ();
    value.enableTags = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SpiderCorba.SpiderDefinePackage.UploadConfig value)
  {
    ostream.write_wstring (value.vTitleTemp);
    ostream.write_wstring (value.vDescTemp);
    ostream.write_wstring (value.vTagsTemp);
    ostream.write_boolean (value.enableTitle);
    ostream.write_boolean (value.enableDes);
    ostream.write_boolean (value.enableTags);
  }

}
