package SpiderCorba;


/**
* SpiderCorba/_YoutubeAgentStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, July 13, 2018 9:28:06 AM ICT
*/

public class _YoutubeAgentStub extends org.omg.CORBA.portable.ObjectImpl implements SpiderCorba.YoutubeAgent
{

  public void getChannelInfo (String channelId, org.omg.CORBA.StringHolder channelName, org.omg.CORBA.IntHolder videoNumber, org.omg.CORBA.IntHolder viewNUmber, org.omg.CORBA.IntHolder subcriber, org.omg.CORBA.IntHolder dateCreated, org.omg.CORBA.IntHolder status)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getChannelInfo", true);
                $out.write_wstring (channelId);
                $in = _invoke ($out);
                channelName.value = $in.read_wstring ();
                videoNumber.value = $in.read_long ();
                viewNUmber.value = $in.read_long ();
                subcriber.value = $in.read_long ();
                dateCreated.value = $in.read_long ();
                status.value = $in.read_long ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getChannelInfo (channelId, channelName, videoNumber, viewNUmber, subcriber, dateCreated, status        );
            } finally {
                _releaseReply ($in);
            }
  } // getChannelInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SpiderCorba/YoutubeAgent:1.0", 
    "IDL:SpiderCorba/SpiderDefine:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _YoutubeAgentStub
