package SpiderCorba;


/**
* SpiderCorba/YoutubeAgentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, July 13, 2018 9:28:06 AM ICT
*/

public interface YoutubeAgentOperations  extends SpiderCorba.SpiderDefineOperations
{
  void getChannelInfo (String channelId, org.omg.CORBA.StringHolder channelName, org.omg.CORBA.IntHolder videoNumber, org.omg.CORBA.IntHolder viewNUmber, org.omg.CORBA.IntHolder subcriber, org.omg.CORBA.IntHolder dateCreated, org.omg.CORBA.IntHolder status);
} // interface YoutubeAgentOperations
