package SpiderCorba;


/**
* SpiderCorba/AgentSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 20, 2018 4:30:11 PM ICT
*/

public interface AgentSideOperations  extends SpiderCorba.SpiderDefineOperations
{

  //Download app function
  void onDownloadStartup (String downloadClusterId);
  long getLastSyncTime (int mappingId);
  void updateLastSyntime (int mappingId, long lastSyncTime);
  void updateDownloadedVideo (SpiderCorba.SpiderDefinePackage.VideoInfo vInfo);
} // interface AgentSideOperations
