package SpiderCorba;


/**
* SpiderCorba/AgentSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, July 26, 2018 4:57:47 PM ICT
*/

public interface AgentSide extends AgentSideOperations, SpiderCorba.SpiderDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgentSide
