package SpiderCorba;


/**
* SpiderCorba/AgentSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Saturday, June 16, 2018 10:22:14 PM ICT
*/

public interface AgentSide extends AgentSideOperations, SpiderCorba.SpiderDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgentSide
