package SpiderCorba;


/**
* SpiderCorba/AgentSidePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 22, 2018 2:54:03 PM ICT
*/

public abstract class AgentSidePOA extends org.omg.PortableServer.Servant
 implements SpiderCorba.AgentSideOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("onDownloadStartup", new java.lang.Integer (0));
    _methods.put ("getLastSyncTime", new java.lang.Integer (1));
    _methods.put ("updateLastSyntime", new java.lang.Integer (2));
    _methods.put ("updateDownloadedVideo", new java.lang.Integer (3));
    _methods.put ("getDownloadConfig", new java.lang.Integer (4));
    _methods.put ("getCustomVideo", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Download app function
       case 0:  // SpiderCorba/AgentSide/onDownloadStartup
       {
         String downloadClusterId = in.read_wstring ();
         this.onDownloadStartup (downloadClusterId);
         out = $rh.createReply();
         break;
       }

       case 1:  // SpiderCorba/AgentSide/getLastSyncTime
       {
         int mappingId = in.read_long ();
         long $result = (long)0;
         $result = this.getLastSyncTime (mappingId);
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 2:  // SpiderCorba/AgentSide/updateLastSyntime
       {
         int mappingId = in.read_long ();
         long lastSyncTime = in.read_longlong ();
         this.updateLastSyntime (mappingId, lastSyncTime);
         out = $rh.createReply();
         break;
       }

       case 3:  // SpiderCorba/AgentSide/updateDownloadedVideo
       {
         SpiderCorba.SpiderDefinePackage.VideoInfo vInfo = SpiderCorba.SpiderDefinePackage.VideoInfoHelper.read (in);
         this.updateDownloadedVideo (vInfo);
         out = $rh.createReply();
         break;
       }

       case 4:  // SpiderCorba/AgentSide/getDownloadConfig
       {
         int mappingId = in.read_long ();
         SpiderCorba.SpiderDefinePackage.DownloadConfig $result = null;
         $result = this.getDownloadConfig (mappingId);
         out = $rh.createReply();
         SpiderCorba.SpiderDefinePackage.DownloadConfigHelper.write (out, $result);
         break;
       }

       case 5:  // SpiderCorba/AgentSide/getCustomVideo
       {
         String downloadClusterId = in.read_wstring ();
         SpiderCorba.SpiderDefinePackage.CustomVideoInfor $result = null;
         $result = this.getCustomVideo (downloadClusterId);
         out = $rh.createReply();
         SpiderCorba.SpiderDefinePackage.CustomVideoInforHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SpiderCorba/AgentSide:1.0", 
    "IDL:SpiderCorba/SpiderDefine:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AgentSide _this() 
  {
    return AgentSideHelper.narrow(
    super._this_object());
  }

  public AgentSide _this(org.omg.CORBA.ORB orb) 
  {
    return AgentSideHelper.narrow(
    super._this_object(orb));
  }


} // class AgentSidePOA
