package SpiderCorba;


/**
* SpiderCorba/DownloadSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 15, 2018 7:14:53 PM ICT
*/

public interface DownloadSideOperations  extends SpiderCorba.SpiderDefineOperations
{
  boolean createDownloadJob (int jobId, SpiderCorba.DownloadSidePackage.DownloadConfig downloadCfg);
  boolean modifyDownloadJob (int jobId, SpiderCorba.DownloadSidePackage.DownloadConfig downloadCfg);
  boolean deleteDownloadJob (int jobId, String downloadClusterId);
} // interface DownloadSideOperations
