package SpiderCorba;


/**
* SpiderCorba/DownloadSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 22, 2018 9:58:23 PM ICT
*/

public interface DownloadSideOperations  extends SpiderCorba.SpiderDefineOperations
{
  boolean createDownloadTimer (int timerId, int timerInterval);
  boolean modifyDownloadTimer (int timerId, int timerInterval, int syncStatus);
  boolean deleteDowloadTimer (int timerId);
  boolean deleteDownloadedVideo (int jobId);
} // interface DownloadSideOperations
