package SpiderCorba;


/**
* SpiderCorba/DownloadSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 7, 2018 2:08:52 PM ICT
*/

public interface DownloadSide extends DownloadSideOperations, SpiderCorba.SpiderDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface DownloadSide
