package SpiderCorba;


/**
* SpiderCorba/DownloadSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 20, 2018 4:30:11 PM ICT
*/

public interface DownloadSide extends DownloadSideOperations, SpiderCorba.SpiderDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface DownloadSide
