package SpiderCorba;


/**
* SpiderCorba/SpiderDefine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, July 26, 2018 4:57:47 PM ICT
*/

public interface SpiderDefine extends SpiderDefineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SpiderDefine
