package SpiderCorba;


/**
* SpiderCorba/SpiderDefineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 15, 2018 7:14:53 PM ICT
*/

public interface SpiderDefineOperations 
{
} // interface SpiderDefineOperations
