package SpiderCorba;


/**
* SpiderCorba/SpiderDefine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 22, 2018 2:54:03 PM ICT
*/

public interface SpiderDefine extends SpiderDefineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SpiderDefine
