
//IDL for java server side
module SpiderDownloadApp
{
  interface SpiderFootSide
  {
        boolean createMappingChannel(in long timerId, in string cHomeId, in string cMonitorId, in string downloadClusterId, in long timerInterval );
        boolean modifyMappingChannel(in long timerId, in string cHomeId, in string cMonitorId, in string downloadClusterId, in long timerInterval, in long synStatus);
        boolean deleteMappingChannel(in long timerId, in string downloadClusterId);

  };
};

module SpiderRenderApp
{
  interface SpiderFootSide
  {
        boolean createRenderJob(in long timerId, in string renderClusterId);
        boolean modifyRenderJob(in long timerId, in string renderClusterId);
        boolean deleteRenderJob(in long timerId, in string renderClusterId);

  };
};

module SpiderUploadApp
{
  interface SpiderFootSide
  {
        boolean createUploadJob(in long timerId, in string uploadClusterId);
        boolean modifyUploadJob(in long timerId, in string uploadClusterId);
        boolean deleteUploadJob(in long timerId, in string uploadClusterId);

  };
};
//IDL for C++ server side

module SpiderAgentApp
{
  interface AgentSide
  {
    struct VideoInfo {
      string videoId;
      string title;
      string tags;
      string description;
      string thumbnail;
      string vDownloadPath;
      string vRenderPath;
      string homeChannelId;
      string monitorChannelId;
      long processStatus;
      long license;
    };

    void onDownloadStartup(in string appId);
    void onRenderStartup(in string appId);
    void onUploadStartup(in string appId);

    long long getLastSyncTime(in long mappingId);
    void updateLastSyntime(in long mappingId, in long long lastSyncTime);

    void updateDownloadedVideo(in VideoInfo vInfo);
    void updateRenderedVideo(in long videoId, in long processStatus, in string videoLocation);
    void updateUploadedVideo (in long videoId, in long processStatus, in string videoLocation);
  };
};
