package SpiderRenderApp.SpiderFootSidePackage;


/**
* SpiderRenderApp/SpiderFootSidePackage/RenderInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 1, 2018 11:19:16 AM ICT
*/

public final class RenderInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int jobId = (int)0;
  public String videoId = null;
  public String vIntro = null;
  public String vOutro = null;
  public String vLogo = null;
  public String vdownloadPath = null;

  public RenderInfo ()
  {
  } // ctor

  public RenderInfo (int _jobId, String _videoId, String _vIntro, String _vOutro, String _vLogo, String _vdownloadPath)
  {
    jobId = _jobId;
    videoId = _videoId;
    vIntro = _vIntro;
    vOutro = _vOutro;
    vLogo = _vLogo;
    vdownloadPath = _vdownloadPath;
  } // ctor

} // class RenderInfo
