module SpiderCorba
{
  interface SpiderDefine
  {
     struct VideoInfo
     {
          wstring videoId;
          wstring title;
          wstring tags;
          wstring description;
          wstring thumbnail;
          wstring vDownloadPath;
          wstring vRenderPath;
          long mappingId;
          long processStatus;
          long license;
    };

    struct DownloadConfig
    {
            wstring cHomeId;
            wstring monitorContent;
            wstring downloadClusterId;
            long mappingType;
            long timerInterval;
            long synStatus;
    };
  };

  interface DownloadSide : SpiderDefine
  {
        boolean createDownloadTimer(in long timerId, in DownloadConfig downloadCfg);
        boolean modifyDownloadTimer(in long timerId, in DownloadConfig downloadCfg);
        boolean deleteDowloadTimer(in long timerId);
        boolean deleteDownloadedVideo(in long jobId);
  };

  interface AgentSide : SpiderDefine
  {
      //Download app function
      void onDownloadStartup(in wstring downloadClusterId);
      long long getLastSyncTime(in long mappingId);
      void updateLastSyntime(in long mappingId, in long long lastSyncTime);
      void updateDownloadedVideo(in VideoInfo vInfo);
  };
};
