module SpiderCorba
{
  interface SpiderDefine
  {
     struct VideoInfo
     {
          wstring videoId;
          wstring title;
          wstring tags;
          wstring description;
          wstring thumbnail;
          wstring vDownloadPath;
          wstring vRenderPath;
          long mappingId;
          long processStatus;
          long license;
    };

    struct DownloadConfig
    {
            wstring cHomeId;
            wstring monitorContent;
            long mappingType;
    };

    struct CustomVideoInfor
    {
            long id;
            wstring videoId;
            long mappingId;
    };
  };

  interface DownloadSide : SpiderDefine
  {
        boolean createDownloadTimer(in long timerId, in long timerInterval);
        boolean modifyDownloadTimer(in long timerId, in long timerInterval, in long syncStatus);
        boolean deleteDowloadTimer(in long timerId);
        boolean deleteDownloadedVideo(in long jobId);
  };

  interface AgentSide : SpiderDefine
  {
      //Download app function
      void onDownloadStartup(in wstring downloadClusterId);
      long long getLastSyncTime(in long mappingId);
      void updateLastSyntime(in long mappingId, in long long lastSyncTime);
      void insertDownloadedVideo(in VideoInfo vInfo);
      void updateDownloadedVideo(in long jobId, in VideoInfo vInfo);
      DownloadConfig getDownloadConfig(in long mappingId);
      CustomVideoInfor getCustomVideo(in wstring downloadClusterId);
  };
};

