
//IDL for java server side
module SpiderDownloadApp
{
  interface SpiderFootSide
  {
        boolean createMappingChannel(in long timerId, in wstring cHomeId, in wstring cMonitorId, in wstring downloadClusterId, in long timerInterval );
        boolean modifyMappingChannel(in long timerId, in wstring cHomeId, in wstring cMonitorId, in wstring downloadClusterId, in long timerInterval, in long synStatus);
        boolean deleteMappingChannel(in long timerId, in wstring downloadClusterId);

  };
};
//IDL for C++ server side

module SpiderAgentApp
{
  interface AgentSide
  {
    struct VideoInfo {
      wstring videoId;
      wstring title;
      wstring tags;
      wstring description;
      wstring thumbnail;
      wstring vDownloadPath;
      wstring vRenderPath;
      long mappingId;
      long processStatus;
      long license;
    };

    void onDownloadStartup(in wstring appId);
    void onRenderStartup(in wstring appId);
    void onUploadStartup(in wstring appId);

    long long getLastSyncTime(in long mappingId);
    void updateLastSyntime(in long mappingId, in long long lastSyncTime);

    void updateDownloadedVideo(in VideoInfo vInfo);
    void updateRenderedVideo(in long jobId, in long processStatus, in wstring vRenderPath);
    void updateUploadedVideo (in long jobId);
	wstring getMonitorChannelId(in long mappingId);
  };
};


