package SpiderCorba.RenderSidePackage;

/**
* SpiderCorba/RenderSidePackage/RenderConfigHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 7, 2018 2:19:30 PM ICT
*/

public final class RenderConfigHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderCorba.RenderSidePackage.RenderConfig value = null;

  public RenderConfigHolder ()
  {
  }

  public RenderConfigHolder (SpiderCorba.RenderSidePackage.RenderConfig initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderCorba.RenderSidePackage.RenderConfigHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderCorba.RenderSidePackage.RenderConfigHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderCorba.RenderSidePackage.RenderConfigHelper.type ();
  }

}
