package SpiderCorba.SpiderDefinePackage;


/**
* SpiderCorba/SpiderDefinePackage/RenderConfigHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Wednesday, June 20, 2018 6:12:05 PM ICT
*/

abstract public class RenderConfigHelper
{
  private static String  _id = "IDL:SpiderCorba/SpiderDefine/RenderConfig:1.0";

  public static void insert (org.omg.CORBA.Any a, SpiderCorba.SpiderDefinePackage.RenderConfig that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SpiderCorba.SpiderDefinePackage.RenderConfig extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "vIntroTemp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "vOutroTemp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "vLogoTemp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "enableIntro",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "enableOutro",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[5] = new org.omg.CORBA.StructMember (
            "enableLogo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (SpiderCorba.SpiderDefinePackage.RenderConfigHelper.id (), "RenderConfig", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SpiderCorba.SpiderDefinePackage.RenderConfig read (org.omg.CORBA.portable.InputStream istream)
  {
    SpiderCorba.SpiderDefinePackage.RenderConfig value = new SpiderCorba.SpiderDefinePackage.RenderConfig ();
    value.vIntroTemp = istream.read_wstring ();
    value.vOutroTemp = istream.read_wstring ();
    value.vLogoTemp = istream.read_wstring ();
    value.enableIntro = istream.read_boolean ();
    value.enableOutro = istream.read_boolean ();
    value.enableLogo = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SpiderCorba.SpiderDefinePackage.RenderConfig value)
  {
    ostream.write_wstring (value.vIntroTemp);
    ostream.write_wstring (value.vOutroTemp);
    ostream.write_wstring (value.vLogoTemp);
    ostream.write_boolean (value.enableIntro);
    ostream.write_boolean (value.enableOutro);
    ostream.write_boolean (value.enableLogo);
  }

}
