package SpiderAgentApp.AgentSidePackage;


/**
* SpiderAgentApp/AgentSidePackage/ClusterInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Monday, June 4, 2018 1:54:10 PM ICT
*/

public final class ClusterInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String clusterId = null;
  public String clusterIP = null;
  public String userName = null;
  public String password = null;
  public short port = (short)0;

  public ClusterInfo ()
  {
  } // ctor

  public ClusterInfo (String _clusterId, String _clusterIP, String _userName, String _password, short _port)
  {
    clusterId = _clusterId;
    clusterIP = _clusterIP;
    userName = _userName;
    password = _password;
    port = _port;
  } // ctor

} // class ClusterInfo
