package SpiderDownloadApp;


/**
* SpiderDownloadApp/SpiderFootSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, May 31, 2018 5:26:47 PM ICT
*/

public interface SpiderFootSideOperations 
{
  boolean createMappingChannel (int timerId, String cHomeId, String cMonitorId, String downloadClusterId, int timerInterval);
  boolean modifyMappingChannel (int timerId, String cHomeId, String cMonitorId, String downloadClusterId, int timerInterval, int synStatus);
  boolean deleteMappingChannel (int timerId, String downloadClusterId);
} // interface SpiderFootSideOperations
