package SpiderDownloadApp;


/**
* SpiderDownloadApp/SpiderFootSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, May 24, 2018 4:13:01 PM ICT
*/

public interface SpiderFootSide extends SpiderFootSideOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SpiderFootSide
