package SpiderDownloadApp;


/**
* SpiderDownloadApp/SpiderFootSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/SpiderAgentAPI.idl
* Saturday, May 19, 2018 10:02:58 AM ICT
*/

public interface SpiderFootSideOperations 
{
  boolean createMappingChannel (int timerId, String cHomeId, String cMonitorId, int timerInterval);
  boolean modifyMappingChannel (int timerId, String cHomeId, String cMonitorId, int timerInterval, int synStatus);
  boolean deleteMappingChannel (int timerId);
} // interface SpiderFootSideOperations
