package SpiderAgentApp;


/**
* SpiderAgentApp/AgentSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Monday, June 4, 2018 3:41:36 PM ICT
*/

public interface AgentSide extends AgentSideOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgentSide
