package SpiderCorba.AgentSidePackage;

/**
* SpiderCorba/AgentSidePackage/AuthenInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 7, 2018 2:19:30 PM ICT
*/

public final class AuthenInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderCorba.AgentSidePackage.AuthenInfo value = null;

  public AuthenInfoHolder ()
  {
  }

  public AuthenInfoHolder (SpiderCorba.AgentSidePackage.AuthenInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderCorba.AgentSidePackage.AuthenInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderCorba.AgentSidePackage.AuthenInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderCorba.AgentSidePackage.AuthenInfoHelper.type ();
  }

}
