package SpiderCorba.AgentSidePackage;

/**
* SpiderCorba/AgentSidePackage/ClusterInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 7, 2018 2:19:30 PM ICT
*/

public final class ClusterInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public SpiderCorba.AgentSidePackage.ClusterInfo value = null;

  public ClusterInfoHolder ()
  {
  }

  public ClusterInfoHolder (SpiderCorba.AgentSidePackage.ClusterInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SpiderCorba.AgentSidePackage.ClusterInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SpiderCorba.AgentSidePackage.ClusterInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SpiderCorba.AgentSidePackage.ClusterInfoHelper.type ();
  }

}
