package SpiderCorba;


/**
* SpiderCorba/AgentSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Monday, July 30, 2018 10:51:16 AM ICT
*/

public interface AgentSide extends AgentSideOperations, SpiderCorba.SpiderDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgentSide
