package SpiderCorba;


/**
* SpiderCorba/AgentSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Monday, July 30, 2018 10:51:16 AM ICT
*/

public interface AgentSideOperations  extends SpiderCorba.SpiderDefineOperations
{

  //Upload app function
  void onUploadStartup (String uploadClusterId);
  SpiderCorba.SpiderDefinePackage.UploadConfig getUploadConfig (int mappingId);
  void updateUploadedVideo (int jobId);

  //Other function
  SpiderCorba.SpiderDefinePackage.AuthenInfo getAuthenInfo (int mappingId);
  SpiderCorba.SpiderDefinePackage.ClusterInfo getClusterInfo (int mappingId, int clusterType);
} // interface AgentSideOperations
