package SpiderCorba;


/**
* SpiderCorba/SpiderDefine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Monday, July 30, 2018 10:51:16 AM ICT
*/

public interface SpiderDefine extends SpiderDefineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SpiderDefine
