package SpiderCorba;


/**
* SpiderCorba/UploadSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Friday, June 15, 2018 7:08:29 PM ICT
*/

public interface UploadSideOperations  extends SpiderCorba.SpiderDefineOperations
{
  boolean createUploadTimer (String timerId, String uploadClusterId);
  boolean modifyUploadTimer (String timerId, String uploadClusterId, int synStatus, SpiderCorba.UploadSidePackage.UploadConfig uploadCfg);
  boolean deleteUploadTimer (String timerId, String uploadClusterId);
  boolean createUploadJob (int jobId, SpiderCorba.SpiderDefinePackage.VideoInfo vInfo, SpiderCorba.UploadSidePackage.UploadConfig uploadCfg);
  boolean deleteUploadJob (int jobId, String uploadClusterId);
} // interface UploadSideOperations
