package SpiderCorba;


/**
* SpiderCorba/UploadSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 21, 2018 10:14:48 AM ICT
*/

public interface UploadSide extends UploadSideOperations, SpiderCorba.SpiderDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface UploadSide
