package SpiderCorba;


/**
* SpiderCorba/UploadSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Sunday, June 17, 2018 9:15:03 AM ICT
*/

public interface UploadSide extends UploadSideOperations, SpiderCorba.SpiderDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface UploadSide
