package SpiderCorba;


/**
* SpiderCorba/UploadSidePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Thursday, June 7, 2018 2:10:52 PM ICT
*/

public abstract class UploadSidePOA extends org.omg.PortableServer.Servant
 implements SpiderCorba.UploadSideOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createUploadJob", new java.lang.Integer (0));
    _methods.put ("deleteUploadJob", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SpiderCorba/UploadSide/createUploadJob
       {
         int jobId = in.read_long ();
         SpiderCorba.SpiderDefinePackage.VideoInfo vInfo = SpiderCorba.SpiderDefinePackage.VideoInfoHelper.read (in);
         SpiderCorba.UploadSidePackage.UploadConfig uploadCfg = SpiderCorba.UploadSidePackage.UploadConfigHelper.read (in);
         boolean $result = false;
         $result = this.createUploadJob (jobId, vInfo, uploadCfg);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // SpiderCorba/UploadSide/deleteUploadJob
       {
         int jobId = in.read_long ();
         String uploadClusterId = in.read_wstring ();
         boolean $result = false;
         $result = this.deleteUploadJob (jobId, uploadClusterId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SpiderCorba/UploadSide:1.0", 
    "IDL:SpiderCorba/SpiderDefine:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public UploadSide _this() 
  {
    return UploadSideHelper.narrow(
    super._this_object());
  }

  public UploadSide _this(org.omg.CORBA.ORB orb) 
  {
    return UploadSideHelper.narrow(
    super._this_object(orb));
  }


} // class UploadSidePOA
