package SpiderRenderApp;


/**
* SpiderRenderApp/SpiderFootSideOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/SpiderAgentAPI.idl
* Monday, May 28, 2018 5:00:42 PM ICT
*/

public interface SpiderFootSideOperations 
{
  boolean createRenderJob (int timerId, String renderClusterId);
  boolean modifyRenderJob (int timerId, String renderClusterId);
  boolean deleteRenderJob (int timerId, String renderClusterId);
} // interface SpiderFootSideOperations
