
//IDL for java server side
module SpiderRenderApp
{
  interface SpiderFootSide
  {
        struct RenderInfo
        {
            long jobId;
            wstring videoId;
            wstring vIntro;
            wstring vOutro;
            wstring vLogo;
            boolean enableIntro;
            boolean enableOutro;
            boolean enableLogo;
            wstring vLocation;
        };

        boolean createRenderJob(in RenderInfo vInfo);
  };
};

//IDL for C++ server side

module SpiderAgentApp
{
  interface AgentSide
  {
    struct VideoInfo {
      wstring videoId;
      wstring title;
      wstring tags;
      wstring description;
      wstring thumbnail;
      wstring vDownloadPath;
      wstring vRenderPath;
      long mappingId;
      long processStatus;
      long license;
    };

    void onDownloadStartup(in wstring appId);
    void onRenderStartup(in wstring appId);
    void onUploadStartup(in wstring appId);

    long long getLastSyncTime(in long mappingId);
    void updateLastSyntime(in long mappingId, in long long lastSyncTime);

    void updateDownloadedVideo(in VideoInfo vInfo);
    void updateRenderedVideo(in long jobId, in long processStatus, in wstring vRenderPath);
    void updateUploadedVideo (in long jobId);
	string getMonitorChannelId(in long mappingId);
  };
};

