module SpiderCorba
{
  interface SpiderDefine
  {
     struct VideoInfo
     {
          wstring videoId;
          wstring title;
          wstring tags;
          wstring description;
          wstring thumbnail;
          wstring vDownloadPath;
          wstring vRenderPath;
          long mappingId;
          long mappingType;
          long processStatus;
          long license;
    };

    struct RenderConfig
    {
            wstring vIntroTemp;
            wstring vOutroTemp;
            wstring vLogoTemp;
            boolean enableIntro;
            boolean enableOutro;
            boolean enableLogo;
    };
  };

  interface RenderSide : SpiderDefine
  {
        boolean createRenderJob(in long jobId, in VideoInfo vInfo);
        boolean deleteRenderJob(in long jobId);
        void deleteRenderdVideo(in wstring vLocation);
  };


  interface AgentSide : SpiderDefine
  {
      //Render app function
      void onRenderStartup(in wstring renderClusterId);
      RenderConfig getRenderConfig(in long mappingId, in long mappingType);
      void updateRenderedVideo(in long jobId, in VideoInfo vInfo);

  };
};
