package corba;


/**
* corba/_AgentSideStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

public class _AgentSideStub extends org.omg.CORBA.portable.ObjectImpl implements corba.AgentSide
{


  //Download app function
  public void onDownloadStartup (String downloadClusterId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("onDownloadStartup", true);
                $out.write_wstring (downloadClusterId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                onDownloadStartup (downloadClusterId        );
            } finally {
                _releaseReply ($in);
            }
  } // onDownloadStartup

  public long getLastSyncTime (int mappingId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLastSyncTime", true);
                $out.write_long (mappingId);
                $in = _invoke ($out);
                long $result = $in.read_longlong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLastSyncTime (mappingId        );
            } finally {
                _releaseReply ($in);
            }
  } // getLastSyncTime

  public void updateLastSyntime (int mappingId, long lastSyncTime)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateLastSyntime", true);
                $out.write_long (mappingId);
                $out.write_longlong (lastSyncTime);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updateLastSyntime (mappingId, lastSyncTime        );
            } finally {
                _releaseReply ($in);
            }
  } // updateLastSyntime

  public void insertDownloadedVideo (corba.variableDefinePackage.VideoInfo vInfo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertDownloadedVideo", true);
                corba.variableDefinePackage.VideoInfoHelper.write ($out, vInfo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                insertDownloadedVideo (vInfo        );
            } finally {
                _releaseReply ($in);
            }
  } // insertDownloadedVideo

  public void updateDownloadedVideo (int jobId, corba.variableDefinePackage.VideoInfo vInfo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateDownloadedVideo", true);
                $out.write_long (jobId);
                corba.variableDefinePackage.VideoInfoHelper.write ($out, vInfo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updateDownloadedVideo (jobId, vInfo        );
            } finally {
                _releaseReply ($in);
            }
  } // updateDownloadedVideo

  public corba.variableDefinePackage.DownloadConfig getDownloadConfig (int mappingId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getDownloadConfig", true);
                $out.write_long (mappingId);
                $in = _invoke ($out);
                corba.variableDefinePackage.DownloadConfig $result = corba.variableDefinePackage.DownloadConfigHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getDownloadConfig (mappingId        );
            } finally {
                _releaseReply ($in);
            }
  } // getDownloadConfig

  public corba.variableDefinePackage.CustomVideoInfor getCustomVideo (String downloadClusterId, int timerId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCustomVideo", true);
                $out.write_wstring (downloadClusterId);
                $out.write_long (timerId);
                $in = _invoke ($out);
                corba.variableDefinePackage.CustomVideoInfor $result = corba.variableDefinePackage.CustomVideoInforHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCustomVideo (downloadClusterId, timerId        );
            } finally {
                _releaseReply ($in);
            }
  } // getCustomVideo


  //Render app function
  public void onRenderStartup (String renderClusterId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("onRenderStartup", true);
                $out.write_wstring (renderClusterId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                onRenderStartup (renderClusterId        );
            } finally {
                _releaseReply ($in);
            }
  } // onRenderStartup

  public corba.variableDefinePackage.RenderConfig getRenderConfig (int mappingId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRenderConfig", true);
                $out.write_long (mappingId);
                $in = _invoke ($out);
                corba.variableDefinePackage.RenderConfig $result = corba.variableDefinePackage.RenderConfigHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRenderConfig (mappingId        );
            } finally {
                _releaseReply ($in);
            }
  } // getRenderConfig

  public void updateRenderedVideo (int jobId, corba.variableDefinePackage.VideoInfo vInfo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateRenderedVideo", true);
                $out.write_long (jobId);
                corba.variableDefinePackage.VideoInfoHelper.write ($out, vInfo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updateRenderedVideo (jobId, vInfo        );
            } finally {
                _releaseReply ($in);
            }
  } // updateRenderedVideo


  //Upload app function
  public void onUploadStartup (String uploadClusterId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("onUploadStartup", true);
                $out.write_wstring (uploadClusterId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                onUploadStartup (uploadClusterId        );
            } finally {
                _releaseReply ($in);
            }
  } // onUploadStartup

  public corba.variableDefinePackage.UploadConfig getUploadConfig (int mappingId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getUploadConfig", true);
                $out.write_long (mappingId);
                $in = _invoke ($out);
                corba.variableDefinePackage.UploadConfig $result = corba.variableDefinePackage.UploadConfigHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getUploadConfig (mappingId        );
            } finally {
                _releaseReply ($in);
            }
  } // getUploadConfig

  public void updateUploadedVideo (int jobId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateUploadedVideo", true);
                $out.write_long (jobId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updateUploadedVideo (jobId        );
            } finally {
                _releaseReply ($in);
            }
  } // updateUploadedVideo


  //Other function
  public corba.variableDefinePackage.AuthenInfo getAuthenInfo (int mappingId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAuthenInfo", true);
                $out.write_long (mappingId);
                $in = _invoke ($out);
                corba.variableDefinePackage.AuthenInfo $result = corba.variableDefinePackage.AuthenInfoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAuthenInfo (mappingId        );
            } finally {
                _releaseReply ($in);
            }
  } // getAuthenInfo

  public corba.variableDefinePackage.ClusterInfo getClusterInfo (int mappingId, int clusterType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getClusterInfo", true);
                $out.write_long (mappingId);
                $out.write_long (clusterType);
                $in = _invoke ($out);
                corba.variableDefinePackage.ClusterInfo $result = corba.variableDefinePackage.ClusterInfoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getClusterInfo (mappingId, clusterType        );
            } finally {
                _releaseReply ($in);
            }
  } // getClusterInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/AgentSide:1.0", 
    "IDL:corba/variableDefine:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AgentSideStub
