package corba;


/**
* corba/SpiderBootSideHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

abstract public class SpiderBootSideHelper
{
  private static String  _id = "IDL:corba/SpiderBootSide:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.SpiderBootSide that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.SpiderBootSide extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.SpiderBootSideHelper.id (), "SpiderBootSide");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.SpiderBootSide read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SpiderBootSideStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.SpiderBootSide value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.SpiderBootSide narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.SpiderBootSide)
      return (corba.SpiderBootSide)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._SpiderBootSideStub stub = new corba._SpiderBootSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.SpiderBootSide unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.SpiderBootSide)
      return (corba.SpiderBootSide)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._SpiderBootSideStub stub = new corba._SpiderBootSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
