package corba;


/**
* corba/SpiderBootSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SpiderAgentAPI.idl
* Thursday, December 19, 2019 2:43:12 PM ICT
*/

public interface SpiderBootSide extends SpiderBootSideOperations, corba.variableDefine, org.omg.CORBA.portable.IDLEntity 
{
} // interface SpiderBootSide
